#ifndef GAME_CONFIG
#define GAME_CONFIG

#define CONFIG_PLAYER_MOVEMENT_SPEED 2.7f
#define CONFIG_PLAYER_INITIAL_HEALTH 150.f
#define CONFIG_PLAYER_SHOOT_DELAY 0.01f
#define CONFIG_PLAYER_KICKBACK 8.5f
#define CONFIG_PLAYER_AMMO 120
#define CONFIG_PLAYER_AMMO_PACK_INIT 3

#define CONFIG_BULLET_DAMAGE 40.f
#define CONFIG_BULLET_LIFETIME 1.1f
#define CONFIG_BULLET_SPEED 4.7f

#define CONFIG_ENEMY_INTIAL_HEALTH 120.f
#define CONFIG_ENEMY_SPEED 3.5f
#define CONFIG_ENEMY_DAMAGE 2.5f
#define CONFIG_ENEMY_SPAWN_DELAY 0.75f

#define CONFIG_AMMO_PACK_LIFETIME 2.25f
#define CONFIG_AMMO_PACK_SPAWN_DELAY 0.7f

#define CONFIG_MAP_ADDITIONAL_STEP 10

#define CONFIG_GAME_MAP_SIZE_X 50
#define CONFIG_GAME_MAP_SIZE_Y 50
#define CONFIG_GAME_WATER_DAMAGE 20.f

#endif